version: '3.9'

services:
  next-app:
    container_name: next-app
    build: ./
    restart: unless-stopped
    #ports:
    #- '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    #env_file:
    #  - .env

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
